name = "CatalogPreprocess"
uuid = "b473eb64-b137-4efd-a9b4-74cb17c049bd"

[deps]
AlgebraOfGraphics = "cbdf2221-f076-402e-a563-3d30da359d67"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Chain = "8be319e6-bccf-4806-a6f7-6fae938471bc"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
OkAoGTutorials = "9aefe428-500e-4e3b-8a70-3d1123ddf76f"
OkFiles = "b25a35d4-863d-483c-9fa1-95480bd075d2"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Shapefile = "8e980c4a-a4fe-5da2-b3a7-4b4b0353a2f4"

[compat]
AlgebraOfGraphics = "0.11, 0.12"
CSV = "0.10"
CairoMakie = "0.15"
Chain = "1.0"
DataFrames = "1.8"
Dates = "1.11"
OkFiles = "0.5"
Pkg = "1.12"
Shapefile = "0.13.3"
julia = "1.10"

[extras]
CompatHelperLocal = "5224ae11-6099-4aaa-941d-3aab004bd678"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Documenter", "CompatHelperLocal"]
